Expansion Hub module
REVrobotics/node-rhsplib pull request #38
Opened 2023-05-03 17:50 UTC by LandryNorris

Created a high level module for expansion hub.

2023-05-03 17:51 UTC, LandryNorris commented
Depends on #37

2023-05-04 16:30 UTC, LandryNorris commented
Renamed the old 'RevHub' interface to 'ExpansionHub' for better future-proofing.

2023-05-08 15:56 UTC, NoahAndrews requested changes

2023-05-08 15:56 UTC, NoahAndrews commented on packages/expansion-hub/src/open-rev-hub.ts
> + * Any children of this hub will be automatically discovered and initialized.
This sentence is false. Discovery is only performed to find the parent module

2023-05-08 15:56 UTC, NoahAndrews commented on packages/rhsplib/tsconfig.json
This should only extend the top-level config.

2023-05-08 15:56 UTC, NoahAndrews commented on packages/expansion-hub/tsconfig.json
This should only extend the top-level config.

2023-05-08 16:11 UTC, LandryNorris commented on packages/rhsplib/tsconfig.json
Changed this

2023-05-08 16:11 UTC, LandryNorris commented on packages/expansion-hub/tsconfig.json
Changed this

2023-05-08 16:56 UTC, NoahAndrews approved these changes

2023-05-08 16:58 UTC, merged